name: Testing configuration variables

on:
  workflow_dispatch:

env:
  Cloud: google-Cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Say Hello to swanand
        run: echo "$Greeting $First_Name is using $Cloud with project ${{ vars.PROJECT_ID }}"
        env:
          First_Name: Swanand
