name: Test user input workflow

on:
  workflow_dispatch:
    inputs:
      number1:
        description: "First number"
        default: "0"
        required: true
        type: number
      number2:
        description: "Second number"
        default: "0"
        required: true
        type: number

jobs:
  add_numbers:
    runs-on: ubuntu-latest
    steps:
      - name: Add numbers
        id: sum
        run: echo "::set-output name=sum::$(( inputs.number1 + inputs.number2 ))"

      - name: Display sum
        run: echo "The sum of ${{ inputs.number1 }} and ${{ inputs.number2 }} is ${{ steps.sum.outputs.sum }}"
